apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - wildcard-certificate.yaml

patches:
  - path: patch-ingress-service.yaml
    target:
      kind: HelmRelease
      name: ingress-nginx
      namespace: flux-system
