---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 5m0s
  values:
    tcp:
      "22": "gitlab/gitlab-gitlab-gitlab-shell:22"

    controller:
      service:
        type: LoadBalancer
        # Set static IP for LoadBalancer
        loadBalancerIP: "10.0.50.200"
        annotations:
          io.cilium/lb-ipam-pool: "prod-pool"

        ports:
          http: 80
          https: 443
          ssh: 22
