apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gitlab.yaml
  - gitlab-backup-s3cfg.yaml
  - gitlab-minio-connection.yaml
  - gitlab-rails-secret-manual.yaml
  - gitlab-repo.yaml
  - gitlab-runner-secret.yaml
  - gitlab-smtp-secret.yaml
