apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: ingress-nginx
      version: "4.14.0"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system

  targetNamespace: ingress-nginx
  install:
    createNamespace: true
    crds: CreateReplace
  upgrade:
    crds: CreateReplace

  values:
    tcp:
      "22": "gitlab/gitlab-gitlab-gitlab-shell:22"

    controller:
      service:
        type: LoadBalancer
        # Set static IP for LoadBalancer
        loadBalancerIP: "10.0.50.200"
        annotations:
          io.cilium/lb-ipam-pool: "prod-pool"

        ports:
          http: 80
          https: 443
          ssh: 22

      kind: DaemonSet
      hostNetwork: false # Cilium Service, doesn't need hostNetwork

      ingressClassResource:
        name: nginx
        enabled: true
        default: true
        controllerValue: "k8s.io/ingress-nginx"

      config:
        use-forwarded-headers: "true"
