apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - democratic-csi-iscsi.yaml
  - democratic-csi-repo.yaml
  - ingress-nginx-repo.yaml
  - ingress-nginx.yaml
  - jetstack-repo.yaml
