---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-vollbro-se
  namespace: infrastructure
spec:
  secretName: wildcard-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: "*.staging.vollbro.se"
  dnsNames:
    - "*.staging.vollbro.se"
    - "staging.vollbro.se"
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
