apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - wildcard-certificate.yaml

nameSuffix: -prod

patches:
  - path: patch-cluster-issuer.yaml
    target:
      kind: ClusterIssuer
      name: letsencrypt
