---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

patches:
  - path: patch-cluster-issuer.yaml
    target:
      kind: ClusterIssuer
      name: letsencrypt

  - path: patch-wildcard-certificate.yaml
    target:
      kind: Certificate
      name: wildcard-vollbro-se
