apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-vollbro-se
  namespace: infrastructure
spec:
  commonName: "*.vollbro.se"
  dnsNames:
    - "*.vollbro.se"
    - "vollbro.se"
