---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-vollbro-se
  namespace: infrastructure
spec:
  secretName: wildcard-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: "*.vollbro.se"
  dnsNames:
    - "*.vollbro.se"
    - "vollbro.se"
