apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-wollbro-se
spec:
  secretName: wildcard-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "*.vollbro.se"
  dnsNames:
    - "*.vollbro.se"
    - "vollbro.se"
  secretTemplate:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ""
