name: Terraform CI

on:
  push:
    branches: [ main ]
    paths:
      - 'infrastructure/**'
      - '.github/workflows/terraform-ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'infrastructure/**'
      - '.github/workflows/terraform-ci.yml'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.0

      - name: Terraform fmt
        working-directory: ./infrastructure
        run: terraform fmt -check -recursive

      - name: Terraform init
        working-directory: ./infrastructure/environments/prod
        run: terraform init -backend=false

      - name: Terraform validate
        working-directory: ./infrastructure/environments/prod
        run: terraform validate

      - name: Terraform plan
        working-directory: ./infrastructure/environments/prod
        run: terraform plan
